# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Test
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'
  schedule:
    # Monthly at 7am UTC on the 9th.
    #
    #        ┌───────────── minute (0 - 59)
    #        │ ┌───────────── hour (0 - 23)
    #        │ │ ┌───────────── day of the month (1 - 31)
    #        │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │ │ │ │ │
    #        │ │ │ │ │
    #        │ │ │ │ │
    - cron: '0 7 9 * *'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        php: ['8.3', '8.2', '8.1', '8.0', '7.4', '7.3', '7.2', '7.1', '7.0']
      fail-fast: false
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      "8.3": ${{ steps.test.outputs['php-8.3'] }}
      "8.2": ${{ steps.test.outputs['php-8.2'] }}
      "8.1": ${{ steps.test.outputs['php-8.1'] }}
      "8.0": ${{ steps.test.outputs['php-8.0'] }}
      "7.4": ${{ steps.test.outputs['php-7.4'] }}
      "7.3": ${{ steps.test.outputs['php-7.3'] }}
      "7.2": ${{ steps.test.outputs['php-7.2'] }}
      "7.1": ${{ steps.test.outputs['php-7.1'] }}
      "7.0": ${{ steps.test.outputs['php-7.0'] }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        tools: none
      env:
        fail-fast: true

    - name: Debugging
      run: |
        php --version
        php -m

    - name: Run test
      id: test
      run: |
        ./test.sh | tee $GITHUB_STEP_SUMMARY
        echo "php-${{ matrix.php }}=${{ matrix.php }}" >> $GITHUB_OUTPUT

  results:
    needs: [build]
    name: Results
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Output
        run: |
          echo ${{ needs.build.outputs['8.3'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['8.2'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['8.1'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['8.0'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['7.4'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['7.3'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['7.2'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['7.1'] }} >> $GITHUB_STEP_SUMMARY
          echo ${{ needs.build.outputs['7.0'] }} >> $GITHUB_STEP_SUMMARY
