name: Test
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        php: ['8.1', '7.4', '7.2', '5.6']
      fail-fast: false
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    timeout-minutes: 1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@2.16.0
      with:
        php-version: ${{ matrix.php }}
        coverage: none
      env:
        fail-fast: true

    - name: Debugging
      run: |
        php --version
        php -m

    - name: Run test
      run: ./test.sh
